import Head from "next/head";

export default function Faq() {
  return (
    <div>
      <Head>
        <title>Frequently Asked Questions | The Food Hub</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  );
}
