import Head from "next/head";
import Hero from "../components/homepage/hero";
import PopularCategory from "../components/homepage/popular-category";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The Food Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <PopularCategory />
    </div>
  );
}
